### ISSUE TITLE
Build Error (OneShot)

### ISSUE THREAD

**Issue by NullVoxPopuli** [broccolijs/broccoli-persistent-filter#200]
This is a new one to me, and I don't even know if this is the right repo to report this issue on?

```
 Build Error (OneShot)

components/collapsible/index.ts: /home/runner/work/emberclear/emberclear/client/web/emberclear/components/collapsible/index.ts: unable to use this non-serializable babel config in this node process
        in /tmp/broccoli-3020EI1K66U07kNx/out-02-funnel
        at broccoli-persistent-filter:Babel > [Babel: @emberclear/ui] (Babel: @emberclear/ui)
```
from ci log: https://github.com/NullVoxPopuli/emberclear/pull/922/checks?check_run_id=746347841

on this branch: https://github.com/NullVoxPopuli/emberclear/pull/922
(using v4-alpha ember-cli-typescript and embroider 0.19.0)

maybe cc @chriskrycho and @ef4?
maaaybe related? https://github.com/emberjs/ember-test-waiters/issues/158

**Comment by ef4** [comment]
This looks like an embroider issue. Not related to broccoli-persistent-filter. This issue can be closed.

Most likely you can work around the problem by setting the environment variable `JOBS=1`. But please file an embroider bug.
